apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  ports:
  - port: 80
    targerPort: 80
  selector:
    app: guestbook-ui
---
apiVersion: app/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 2
  revisionRistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: ger.io/helpio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
